@startuml
skinparam defaultTextAlignment center
start
:Получение начальной раскладки, весов M,
 количества итераций С, матрица переходов диграфов;
:Расчет всех критериев для начальной раскладки init;
:Расчет multiplier на основе полученных весов;
:Создание списка кортежей (раскладка, оценки) l_list;
while (Не исчерпано количество итераций C)
    if (Начальное прохождение алгоритма?) then (да)
        :Создание списка поколения gen_list;
        :Добавление init в gen_list; 
    else (нет)
        :Очистка gen_list;
        :Добавление первых n вариантов из l_list в gen_list;
        :Добавление r случайных вариантов из l_list в gen_list;
        :Очистка l_list;
    endif
    while (Итерация по списку gen_list)
        :Извлечение раскладки из списка;
        :Генерация всех возможных попарных перестановок;
        while (Остались попарные перестановки?)
            :Генерация новой раскладки newlayout на основе перестановки;
            :Оценка newlayout по всем критериям;
            :Умножение полученных оценок на multiplier;
            :Добавление кортежа (newlayout, оценки) в список l_list;
        endwhile
    endwhile
:Сортировка списка l_list по возрастанию суммы оценок;
endwhile
:Выбор наилучших варианто из списка l_list;

stop
@enduml