@startuml plan
start
:Чтение датасета;
:Распределение датасета по словарю 
(ключ название символа, 
значение количество употреблений у символа);
:Построение разреженной марицы переходов (символ в символ);
:Построение разреженной матрицы перехода
 символ в символ в пределах одной зоны;
:Определение параметров оценки раскладки;
fork
:Расчет равномерности 
загрузки по зонам;
fork again
:Расчет чередования кистей
 (шаг 1 символ);
fork again
:Расчет процента переходов,
 которые ведут к повторению
  на той же зоне;
fork again
:Расчет процента нажатий, 
которые происходят на стандартных
 положениях пальцев;
end fork
:Построение алгоритма итеративного расчета изменения оценок 
относительно попарных изменений положения символов в раскладке;
repeat
:Расчет изменений оценок относительно перестановок символов по текущей раскладке;
:Выбираем лучшие (несколько штук) перестановки;
:Подаем на вход алгоритму производные раскладки
(с учетом выбранных выше перестановок);
repeat while (Достаточно?)
stop
@enduml