@startuml Uniformity
skinparam defaultTextAlignment center
start
:Получение раскладки и разреженной матрицы переходов, веса R;
:Построение зон согласно 10-пальцевому вводу;
while (Итерация по зонам)
  :Расчет количества нажатий в пределах зоны;
  if (Зона мизинца?) then (да)
    :Умножение количества нажатий на вес R;
  endif 
endwhile (конец итерации)
:Расчет медианы среди количества нажатий по каждой зоне;
:Сумма положительной разницы между текущим и средним
(КолВоНажатийВЗоне - медиана);
:Разделить на всё количество нажатий;

stop
@enduml