
@startuml VAlter 
skinparam defaultTextAlignment center
start
:Получение раскладки и разреженной матрицы переходов;
:Расчет количества переходов,
 вызывающих чередование верхней и нижней строки раскладки;
:Деление на общее количество переходов;
stop
@enduml