@startuml Alteration
start
:Получение раскладки и разреженной матрицы переходов;
:Расчет количества переходов 
из одной половины в другую с шагом в единицу;
:Разделить на общее количество переходов;
end
@enduml