@startuml Alteration
skinparam defaultTextAlignment center
start
:Получение раскладки и разреженной матрицы переходов;
:Расчет количества переходов 
из одной половины в другую;
:Деление на общее количество переходов;
stop
@enduml