@startuml
start
:Получение раскладки и разреженной матрицы переходов;
:Построение зон согласно 10 пальцевому ввода;
repeat
  :Расчет количества нажатий в пределах зоны для каждой зоны;
repeat while (Кончились зоны?)
:Расчет среднего количества символов на каждой зоне;
:Сумма положительной разницы между текущим и средним
(КолВоНажатийВЗоне - СреднееКоличество);
:Разделить на всё количество нажатий;

stop
@enduml